### ISSUE TITLE
Android needs updated

### ISSUE THREAD

**Issue by niftylettuce** [jhabdas/react-native-webpack-starter-kit#10]
Per <https://github.com/facebook/react-native/issues/2983> we need a fresh `react-native init` on the Android folder.  Otherwise you can't run it.

**Comment by jhabdas** [comment]
I'm on it.

**Comment by jhabdas** [comment]
Just dropped https://github.com/jhabdas/react-native-webpack-starter-kit/commit/d6ea6992d3e9fae8b6f4d6cd888a0d35a9d30bcd. I'm not set-up to test Android yet, so I'm hoping someone can confirm this did the trick for them before we close.

**Comment by niftylettuce** [comment]
@jhabdas See <https://github.com/mjohnston/react-native-webpack-server/issues/65#issuecomment-151222398> you might want to add this to `package.json` so that people can run Android on device with this.

**Comment by jhabdas** [comment]
Done. Updated README with credit and links.
