### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by pulpfree** [jhabdas/react-native-webpack-starter-kit#107]
After a fresh install as per README, I get the following error:
`'RCTRootView.h' file not found`
tried downgrading react and react-native with no luck.
Also tried upgrading the ios: 
`'npm install -g rnpm && npm install rnpm-plugin-upgrade@0.26 --save-dev', then run 'rnpm upgrade'`
again no luck.

Thanks,
ron

**Comment by jhabdas** [comment]
@pulpfree thanks for the info. NPM can be a bit finicky, so let's rule that out first. Can you share your `npm -v && node -v` so I can try and reproduce your iOS issue.

**Comment by pulpfree** [comment]
`$ npm -v && node -v
3.8.9
v6.2.0`
Thanks for the quick response @jhabdas , did find something with the react version.
I downgraded react from 15.1.0 to 15.0.2 and the problem resolved.

**Comment by jhabdas** [comment]
Ah yeah. I just recently pinned that. Sorry you encountered it! https://github.com/jhabdas/react-native-webpack-starter-kit/commit/ec9cbfba58e8d1d08da779a2f4c6a345899fadf6

**Comment by pulpfree** [comment]
no worries, glad it's resolved. Great product, just upgraded from last year after project had been on haitus and was anxious to use the webpack plugins.

**Comment by jhabdas** [comment]
@pulpfree that's great to hear! have fun 😄
