### ISSUE TITLE
Error on iOS directly after build success

### ISSUE THREAD

**Issue by captDaylight** [jhabdas/react-native-webpack-starter-kit#120]
I'm using node v4.1.1, cloned repo, ran the installation command (after setting up), then npm start. Opened the xcode file, ran, and shortly after a successful build it showed the red screen with: 

```
undefined
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by jhabdas** [comment]
Will try repro soon. Can you check your installed react and react-native dep versions and share for debugging?

**Comment by captDaylight** [comment]
@jhabdas thanks for the quick reply, where do you want me to get the dep versions from? the output from npm install?

**Comment by jhabdas** [comment]
npm ls | grep react will output them
On Thu, Jun 30, 2016 at 10:30 AM captDaylight <notifications@github.com>
wrote:

> @jhabdas <https://github.com/jhabdas> thanks for the quick reply, where
> do you want me to get the dep versions from? the output from npm install?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/jhabdas/react-native-webpack-starter-kit/issues/120#issuecomment-229695736>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAa36n5mr-q8xlOoNCmPgopBD08_33-6ks5qQ-EjgaJpZM4JCQ5T>
> .
>
-- 
Josh J Habdas
Principal Engineer
Comfusion LLC
tel: +1 (630) 290-3542
http://habd.as

**Comment by captDaylight** [comment]
react-native-webpack-starter-kit@0.1.0 /Users/paulchristophe/projects/native-starter-kit/native-starter-kit
├─┬ babel-preset-react@6.11.1
│ ├─┬ babel-plugin-transform-react-display-name@6.8.0
│ ├─┬ babel-plugin-transform-react-jsx@6.8.0
│ │ ├─┬ babel-helper-builder-react-jsx@6.9.0
│ ├─┬ babel-plugin-transform-react-jsx-self@6.11.0
│ └─┬ babel-plugin-transform-react-jsx-source@6.9.0
├─┬ eslint-plugin-react@5.2.2
├─┬ react@15.1.0
├─┬ react-native@0.28.0
│ │ ├─┬ babel-plugin-transform-react-display-name@6.8.0
│ │ └─┬ babel-plugin-transform-react-jsx@6.8.0
│ │   ├─┬ babel-helper-builder-react-jsx@6.9.0
│ ├─┬ babel-preset-react-native@1.9.0
│ │ ├─┬ babel-plugin-react-transform@2.0.2
│ │ ├─┬ babel-plugin-transform-react-display-name@6.8.0
│ │ ├─┬ babel-plugin-transform-react-jsx@6.8.0
│ │ │ ├─┬ babel-helper-builder-react-jsx@6.9.0
│ │ ├─┬ babel-plugin-transform-react-jsx-source@6.9.0
│ ├── react-clone-referenced-element@1.0.1
│ ├── react-timer-mixin@0.13.3
│ ├─┬ react-transform-hmr@1.0.4
│ │ └─┬ react-proxy@1.1.8
│ │   └── react-deep-force-update@1.0.1
├─┬ react-native-webpack-server@0.9.3

**Comment by jhabdas** [comment]
Thanks again for the report. I used NVM to install node 4.1.1 and was not able to reproduce this issue. You may want to check your environment or reinstall node modules. Good luck!
