### ISSUE TITLE
Can't run android-setup-port

### ISSUE THREAD

**Issue by chrisbenseler** [jhabdas/react-native-webpack-starter-kit#126]
Following the README, i installed the dependencies (npm install) and
_npm run android-setup-port_

gives me the output:

> npm ERR! react-native-webpack-starter-kit@0.1.0 android-setup-port: `adb reverse tcp:8081 tcp:8080`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the react-native-webpack-starter-kit@0.1.0 android-setup-port script 'adb reverse tcp:8081 tcp:8080'.

running node 5.7

Do I have to set anything else?
My device is listed when I do "adb devices" on the CLI.

**Comment by jhabdas** [comment]
The RN packager runs on 8081 after running npm start. Is your packager running?

**Comment by chrisbenseler** [comment]
I've missed that. Thanks, now I'm running it and it's ok.

**Comment by jhabdas** [comment]
No problem. Would it be helpful if I created a video of the application starting? Sometimes it can take a minute and I know that throws people off. Happy hacking!

**Comment by chrisbenseler** [comment]
@jhabdas I don't htink it's necessary. It was my mistake - I was in a hurry and didn't pay enough attention to the steps in the readme file.
