### ISSUE TITLE
Unable to create 'index.ios.js' file

### ISSUE THREAD

**Issue by wbashir** [jhabdas/react-native-webpack-starter-kit#13]
I am unable to successfully start the server and its listening on port `8080`. On running the iOS simulator, the webpack config fails with an abrupt error:

```` Javascript
{"message":"Cannot find entry file index.ios.js in any of the roots: [\"smash\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
```` 

It did however attempt to do something with the log looking something like this:

```` Javascript
Webpack dev server listening at  http://localhost:8082
Hash: 63227c5f29276e627b82
Version: webpack 1.12.9
Time: 14130ms
               Asset     Size  Chunks             Chunk Names
    index.android.js  22.1 kB       0  [emitted]  index.android
        index.ios.js  22.2 kB       1  [emitted]  index.ios
index.android.js.map  25.8 kB       0  [emitted]  index.android
    index.ios.js.map  26.9 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 16.1 kB [rendered]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 16.1 kB [rendered]
webpack: bundle is now VALID.
react-native packager ready...


 ERROR  Packager can't listen on port 8081

`````

**Comment by jhabdas** [comment]
Looks like you have something running on port 8081 already, possibly a hanging process. You can check by terminating the start script used to run this kit then, at a bash prompt, running "lsof -i 8081" to find the Process ID of whatever might be conflicting and then "kill" the process by PID, e.g. "kill -9 2600".  Let me know how it goes.

**Comment by wbashir** [comment]
There seems to be another terminal window that pops up when I run the XCode project. I believe that terminal session might be the issue. Can i safely kill the terminal while the simulator is running?

**Comment by wbashir** [comment]
Never mind!! Looks like it worked this around as I made sure no terminal were running. Thanks for this wonderful starter kit, its awesome!

**Comment by jhabdas** [comment]
Kudos to you. Have fun with it. Love to hear about anything you create! Happy :turkey: day!

**Comment by jhabdas** [comment]
Also, be sure to run "npm start" in a terminal window to start the webpack dev server and react package before running the simulator. Then, when you run the simulator from Xcode, it should detect the running packager instance on 8081 and skip opening another terminal window.

**Comment by diffractometer** [comment]
@wbashir I get annoyed by the second window so I run `react-native start` from my main terminal window, XCode auto detects if it's running or not so you don't get into the situation where you have two terminal windows popping up...

**Comment by wbashir** [comment]
@diffractometer Awesome! man this helped alot

**Comment by jhabdas** [comment]
@wbashir @diffractometer because this kit runs the packager and webpack dev server with `npm start` it shouldn't be necessary to close a secondary window as the packager should detect it's already running and suppress opening a terminal window when the simulator is run. If you're experiencing something different please consider upgrading to the latest version of this kit and let me know if you're still receiving the pop-up window.

**Comment by diffractometer** [comment]
@jhabdas der should have realized that. @wbashir. That is just the default behavior I saw when you setup a new react native app (0.14.1), so something to be aware of...

**Comment by jhabdas** [comment]
@diffractometer Thanks for the additional info. I've saw a similar issue once in the past, which caused me to fork the `react-native-webpack-server` (RWNS) dependency once, though the issue was resolved and I [nuked the fork](https://github.com/jhabdas/react-native-webpack-starter-kit/tree/v1.13.2).

Based on our discussion it's still not clear to me if terminal pop-ups are occurring while running the simulator _once_ the `npm start` command is issued and spins up. But, if so, it's a bug and something worth further investigation, if only an attempt to take the latest RWNS release candidate.

**Comment by wbashir** [comment]
@jhabdas I can confirm this happened to me again in the following sequence.

1) `npm start` (Port 8080) - Session 1
2) Run the simulator in XCode 
3) Another terminal pops up (Session 2).
4) Session 1 fails with port 8081 is being used and the simulator displays 'Red' warning.

**Comment by jhabdas** [comment]
Thanks for the info. To help debug I'll need to know the version of the
starter kit are you using. Xcode and Xcode CLI tools versions as well. And
confirmation the packager doesn't start automatically after Webpack after
some time when "npm start" is run (the expected behavior).

**Comment by jhabdas** [comment]
Thanks for the info @wbashir. To help debug I'll need to know the version of or latest commit of the starter kit you're using. Xcode and Xcode CLI tools versions as well. And confirmation the packager doesn't automatically start after Webpack dev server finishes following issuance of `npm start` at the bash prompt.

**Comment by wbashir** [comment]
Latest Commit:

```` Javascript
commit 9a5c7c8626c7951bcf5c1bfb449f1346fbf59d3c
Author: Spencer Carli <spencercarli@gmail.com>
Date:   Thu Nov 19 20:00:13 2015 -0500

    Update readme
````
XCode Version
`XCode 7.1`

Xcode CLI Tools Version: I was unable to confirm this information with `EL Capitan` but running the following command `xcode-select -p` I got back `/Applications/Xcode.app/Contents/Developer` So i now I have the CLI tools installed. I noticed after starting at the bash prompt (`npm start`), and waiting for a while a message is displayed stating the 'WebPack Dev server is listening on Port ...`?

**Comment by jhabdas** [comment]
That particular commit was made outside this kit as as the author is [not a direct contributor](https://github.com/jhabdas/react-native-webpack-starter-kit/graphs/contributors) nor does the commit appear in my tree. If you clone a fresh copy of this kit and see the issue I'd be happy to assist further. Alternatively, you may want to try setting my kit as the upstream remote for the project you're working on, create a branch, merge from upstream tag https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.15.0, resolve any merge conflicts and try that way to sustain your project.

**Comment by wbashir** [comment]
@jhabdas  I am sorry I was working in the wrong repo when I ran `git log`. I will update my comment and/or reply to show the latest commit I am working with on a clone for this particular repo.

**Comment by jhabdas** [comment]
Cool

**Comment by wbashir** [comment]
```` Javascript
commit d2fde3c80134aece91c22b0c1f493efeb393288c
Merge: 5b79092 661b298
Author: Josh Habdas <jhabdas@gmail.com>
Date:   Tue Dec 1 21:07:29 2015 -0600

    Merge pull request #18 from jhabdas/greenkeeper-eslint-1.10.3
    
    eslint@1.10.3 untested 
`````

After waiting for the webpack dev server to start, I get an error:

```` Javascript

Webpack dev server listening at  http://localhost:8082
Hash: b840a094b552b4593d1f
Version: webpack 1.12.9

 Unknown option: base.stage
    at Logger.error (/smash/node_modules/babel-core/lib/transformation/file/logger.js:41:11)

`````

**Comment by jhabdas** [comment]
To help debug I ran through a fresh clone and install of the app on node `v4.1.0` and npm `3.3.0` on my Air with El Capitan. The only problem I ran into were some missing dependencies from npm on first install, prompting me to run an `npm update` to get the rest of the deps. Upon running `npm start` I see both the dev server and react packager start:

![screen shot 2015-12-03 at 9 51 56 pm](https://cloud.githubusercontent.com/assets/440298/11581554/d19f2ee0-9a08-11e5-97d5-d6ab6e67cc0b.png)

Then, after opening `App.xcodeproj` and running the simulator I see:

![screen shot 2015-12-03 at 9 52 04 pm](https://cloud.githubusercontent.com/assets/440298/11581583/28efee64-9a09-11e5-8682-c9f91543ac10.png)

Sorry if you're having trouble with your environment. You may want to try a fresh clone or work through the [Getting Started guide for RN](https://facebook.github.io/react-native/docs/getting-started.html) one more time to help get things squared away. Good luck!

**Comment by wbashir** [comment]
@jhabdas Perfect, thanks for this information. It gives me some context reference as I had similar issues with another `react-native` app that was caused by my stale environment (node & npm)

**Comment by wbashir** [comment]
@jhabdas How are you able to use npm version `3.3.0'? When I download and install node, the mature and dependable release  through [1], it comes with `npm: v2.14.7`.

[1] https://nodejs.org/en/

**Comment by jhabdas** [comment]
npm i -g npm

But I would suggest staying on npm 2 for now if you can, as v3 is still
quite buggy and slow.

**Comment by wbashir** [comment]
Ok so latest node mature and now dependency error on `npm install`

``` Javascript 
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3

npm ERR! peerinvalid The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 
0.15.0-rc

````

The only difference is my `npm` version but it looks like with the latest version of this clone and its requirements, i am unable to finish a npm `install`?

**Comment by jhabdas** [comment]
When you "npm ls", is it clean? If so you're good to go. The peer dep
shouldn't be a concern.

**Comment by wbashir** [comment]
Yea it's empty. It's very odd that its looking for a peer dependency.. I have done a fresh clone a few times

**Comment by jhabdas** [comment]
Great! RWNS is locked on 15. Once they bump their RN dep version and I bump
them that error will disappear.

**Comment by wbashir** [comment]
Awesome! thanks for tracking that down, I will wait for their update unless their is a pull request reference already

**Comment by wbashir** [comment]
@jhabdas I think this is finally working as expected! Thanks for your patience and by the way what is the cool terminal theme you got there?

**Comment by jhabdas** [comment]
I lifted the terminal theme from @paulmillr https://github.com/jhabdas/dotfiles
