### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by icron** [jhabdas/react-native-webpack-starter-kit#156]
I use docker on windows 10. 

npm WARN cannot run in wd react-native-webpack-starter-kit@0.1.0 npm run snyk-protect (wd=/app)
npm ERR! Linux 4.4.20-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--development"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.29.2 wants react@~15.2.0
npm ERR! peerinvalid Peer react-native-webpack-server@0.9.3 wants react@>=0.14.5

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c cd /tmp &&   wget https://github.com/jhabdas/react-native-webpack-starter-kit/archive/$KIT_VERS.tar.gz &&   mkdir -p /app &&   tar --strip-components=1 -xzf $KIT_VERS.tar.gz -C /app &&   rm -f $KIT_VERS.tar.gz &&   cd /app &&   npm install --$NODE_ENV' returned a non-zero code: 1

**Comment by jhabdas** [comment]
RN is tightly coupled with React as a separate dependency. To fix the issue modify package manifest and give RN the React peer it wants
