### ISSUE TITLE
babel-runtime may be required to run properly

### ISSUE THREAD

**Issue by a-axton** [jhabdas/react-native-webpack-starter-kit#2]
I was running into an issue importing some of my files, was getting the error:

    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/interop-require-default'

The transform 'optional=runtime' requires the babel-runtime package to work properly, more here https://babeljs.io/docs/usage/runtime/

**Comment by jhabdas** [comment]
Hi Andy. What happens if you install babel-runtime module to the project?

npm install babel-runtime --save-dev

**Comment by a-axton** [comment]
it resolved my error after I installed, forgot to mention I was using node v4.1.1

**Comment by jhabdas** [comment]
Cool

**Comment by jhabdas** [comment]
If I hear anymore reports of this issue I'll consider adding the dependency to the manifest. Thanks again!

**Comment by jhabdas** [comment]
@a-axton went ahead and added `babel-runtime` to the manifest since I'm referencing it in the webpack config

**Comment by RyanCCollins** [comment]
Man, I see you everywhere now @jhabdas .,  I just had this same issue, too! Haha.

**Comment by jhabdas** [comment]
^^
