### ISSUE TITLE
Can not get this to even run

### ISSUE THREAD

**Issue by bradynapier** [jhabdas/react-native-webpack-starter-kit#20]
I can not get this to do a thing.  I did the basics, ran , test and i get a white screen with loading from localhost:8080 and nothing else.. nothing happens.

**Comment by bradynapier** [comment]
![image](https://cloud.githubusercontent.com/assets/8041420/11605932/8a8ce622-9ac2-11e5-8f5d-83579aa66853.png)

**Comment by bradynapier** [comment]
I noticed others in the closed issues seem to have the exact same issue.  I cloned this 2 hours ago from this kit so it should be the absolute latest.  I start the webpack server then start simulator and a second pops up immediately.

**Comment by jhabdas** [comment]
Sorry for your troubles. React Native environments can be a little tricky. We just have to be patient.  Some inspiration https://github.com/jhabdas/react-native-webpack-starter-kit/issues/13#issuecomment-161868142
