### ISSUE TITLE
RCTNetwork problem when running a fresh install

### ISSUE THREAD

**Issue by luandro** [jhabdas/react-native-webpack-starter-kit#22]
I know setting up react-native can be really tricky. But when not even Google can help, I don't know where else to turn. Did a fresh clone, installed everything and did a `npm start`. This is what the android emulator spits out:

![screenshot](http://i.imgur.com/P4LnWRU.png)

Xcode also gives me a bunch of errors related to RCTNetwork.

Any clues? Am I missing something. I actually got this to work a few hours ago, but now...

**Comment by jhabdas** [comment]
I'm more familiar with the iOS side. What Node and NPM versions are you
using? And what was your experience earlier?

**Comment by luandro** [comment]
Node 5.0.0 and npm 3.3.6

When I got it to work I don't remember if I had done a pull from the repo. I don't remember when exactly is stopped working, or why, but I've tried a fresh clone and install twice after that, and I always get these warnings about RCTNetworking.

**Comment by luandro** [comment]
Trying to find something [here](https://github.com/facebook/react-native/issues/4488)

**Comment by jhabdas** [comment]
Node 4 and NPM 3 are not very stable or trustworthy yet. If you have NVM
install and use the LTS release (Argon) and back down to NPM 2, blow away
node modules, clear your NPM cache and reinstall.

**Comment by christopherdro** [comment]
@luandro Double check that your on 0.16.

**Comment by luandro** [comment]
Using Node LTS, npm keeps failing with the weirdest errors. I'll try again when I wake up.

0.16.0 Confirmed

**Comment by jhabdas** [comment]
`npm i -g npm@2`

**Comment by luandro** [comment]
Did that, but won't install...

```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 0.15.0-rc
```

**Comment by jhabdas** [comment]
That's expected for the time being. Info as to why covered in #13, if you'd like to understand why. But you should get a clean "npm ls" after install regardless on both NPM 2 and 3, and be able to stand up and run the app. Please let me know how it goes.

**Comment by jhabdas** [comment]
@luandro Any luck with Android and/or getting your environment set-up? I created a chatroom for individuals to connect. Link available from the Gitter badge in [`README.md`](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/README.md).

**Comment by jhabdas** [comment]
@laundro Hope all is well. If this is no longer an issue please let me know or feel free to close this on your own. Thanks!
