### ISSUE TITLE
Unmet dependency (react-native 0.16.0) on fresh install

### ISSUE THREAD

**Issue by diffractometer** [jhabdas/react-native-webpack-starter-kit#23]
Hello Josh,

FYI I'm experiencing an unmet dependency upon a fresh clone of react-native-webpack-starter-kit:

```
npm ERR! peerinvalid The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 0.15.0-rc
```

I fixed by downgrading react-native to 0.15.0.

**Comment by diffractometer** [comment]
Ah - just saw your thread about NPM 3, agreed.

**Comment by jhabdas** [comment]
16 will still work. I'm ahead of the RNWS dep and don't want to fork them
again. That error is expected and OK as long as you get a clean "npm ls"
post install regardless of npm -v

**Comment by diffractometer** [comment]
Got it, thx.
