### ISSUE TITLE
Error: Incompatible clock pointer + port conflict

### ISSUE THREAD

**Issue by diffractometer** [jhabdas/react-native-webpack-starter-kit#24]
Okii one more:

I'm trying a fresh install, I run `npm start` everything works as normal: 

```
> rnws start

Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: 3cda8f6d910dbf541ac4
Version: webpack 1.12.9
Time: 1352ms
               Asset     Size  Chunks             Chunk Names
    index.android.js  22.3 kB       0  [emitted]  index.android
        index.ios.js  22.3 kB       1  [emitted]  index.ios
index.android.js.map  26.2 kB       0  [emitted]  index.android
    index.ios.js.map  27.3 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 16.2 kB [rendered]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 16.2 kB [rendered]
webpack: bundle is now VALID.
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/hunterhusar/dev/learning/react-native-webpack-starter-kit
   /Users/hunterhusar/dev/learning/react-native-webpack-starter-kit/node_modules/react-native-webpack-server/_entry

[5:09:20 PM] <START> Building Dependency Graph
[5:09:20 PM] <START> Crawling File System
[5:09:20 PM] <START> Loading bundles layout
[5:09:20 PM] <END>   Loading bundles layout (1ms)

React packager ready.

react-native packager ready...
[5:09:21 PM] <END>   Crawling File System (1268ms)
[5:09:21 PM] <START> Building in-memory fs for JavaScript
[5:09:21 PM] <END>   Building in-memory fs for JavaScript (430ms)
[5:09:21 PM] <START> Building in-memory fs for Assets
[5:09:22 PM] <END>   Building in-memory fs for Assets (464ms)
[5:09:22 PM] <START> Building Haste Map
[5:09:22 PM] <START> Building (deprecated) Asset Map
[5:09:22 PM] <END>   Building (deprecated) Asset Map (174ms)
[5:09:23 PM] <END>   Building Haste Map (836ms)
[5:09:23 PM] <END>   Building Dependency Graph (3005ms)
```

But when I open the app up in Xcode I see two unexpected behaviors:

1) The secondary [default] terminal window opens up and I get a port conflict (is there a way to prevent this window from starting on build?) with the error `Packager can't listen on port 8081`. 

2) I go ahead and kill the conflicting process and close the secondary terminal window, then re-run `npm start` and re-build the app in Xcode but the build fails with the error:

`Incompatible block pointer types passing 'void (^)(RCTLogLevel, NSString *__strong, NSNumber *__strong, NSString *__strong)' to parameter of type 'RCTLogFunction' (aka 'void (^)(RCTLogLevel, RCTLogSource, NSString *__strong, NSNumber *__strong, NSString *__strong)')`
 
+ npm 3.5.1 
+ node 5.1.1
+ XCode Version 7.1.1 (7B1005)

Do you suggest downgrading npm to version 2?

**Comment by diffractometer** [comment]
The second error is happening in AppTests.m 

```
../AppTests.m:45:21: Incompatible block pointer types passing 'void (^)(RCTLogLevel, NSString *__strong, NSNumber *__strong, NSString *__strong)' to parameter of type 'RCTLogFunction' (aka 'void (^)(RCTLogLevel, RCTLogSource, NSString *__strong, NSNumber *__strong, NSString *__strong)')
```

**Comment by jhabdas** [comment]
You may have more luck [emulating my environment](https://github.com/jhabdas/react-native-webpack-starter-kit/issues/13#issuecomment-161868142), which is using `npm@3`. As long as you're on Xcode 7 you should be good to go with a more stable version of node. If for some reason you have install issues besides any peed dependency errors I'd back down to `npm i -g npm @2`. As for the second terminal window, that's symptomatic of a misconfigured environment.

**Comment by diffractometer** [comment]
Wuh oh. Hmm, I emulated your env: npm@3 and set default node to v4.1.0. Then I ran `npm i` (only seeing the original peer dependency issue, so will ignore), opened the app in XCode and ran `npm start`. 

Still getting the really weird error in AppTests.m `Incompatible block pointer types passing 'void'` Strange....

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>

#import "RCTLog.h"
#import "RCTRootView.h"

#define TIMEOUT_SECONDS 240
#define TEXT_TO_LOOK_FOR @"Welcome to React Native!"

@interface AppTests : XCTestCase

@end

@implementation AppTests

- (BOOL)findSubviewInView:(UIView *)view matching:(BOOL(^)(UIView *view))test
{
  if (test(view)) {
    return YES;
  }
  for (UIView *subview in [view subviews]) {
    if ([self findSubviewInView:subview matching:test]) {
      return YES;
    }
  }
  return NO;
}

- (void)testRendersWelcomeScreen
{
  UIViewController *vc = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
  NSDate *date = [NSDate dateWithTimeIntervalSinceNow:TIMEOUT_SECONDS];
  BOOL foundElement = NO;

  __block NSString *redboxError = nil;
  RCTSetLogFunction(^(RCTLogLevel level, NSString *fileName, NSNumber *lineNumber, NSString *message) {
    if (level >= RCTLogLevelError) {
      redboxError = message;
    }
  });

  while ([date timeIntervalSinceNow] > 0 && !foundElement && !redboxError) {
    [[NSRunLoop mainRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:0.1]];
    [[NSRunLoop mainRunLoop] runMode:NSRunLoopCommonModes beforeDate:[NSDate dateWithTimeIntervalSinceNow:0.1]];

    foundElement = [self findSubviewInView:vc.view matching:^BOOL(UIView *view) {
      if ([view.accessibilityLabel isEqualToString:TEXT_TO_LOOK_FOR]) {
        return YES;
      }
      return NO;
    }];
  }

  RCTSetLogFunction(RCTDefaultLogFunction);

  XCTAssertNil(redboxError, @"RedBox error: %@", redboxError);
  XCTAssertTrue(foundElement, @"Couldn't find element with text '%@' in %d seconds", TEXT_TO_LOOK_FOR, TIMEOUT_SECONDS);
}


@end
```

I've got a several other react native apps setup in this env and they are all working. I tried deleting the derived data in Xcode. I will see if I can reproduce the issue by rebuilding the app from scratch.

**Comment by jhabdas** [comment]
Any luck? I'm considering adding docker support for this repo to help stabilize the environment as Node post 0.12 is still a bit shaky.

**Comment by diffractometer** [comment]
Word. Tried to build from scratch on an entirely different computer with same build and env, ran into same error... real head scratcher!

<img width="740" alt="screen shot 2015-12-09 at 12 20 26 am" src="https://cloud.githubusercontent.com/assets/955590/11678158/bcc5b8e4-9e0a-11e5-9000-5c2308e364dc.png">

**Comment by diffractometer** [comment]
I'm trying to rebuild... I think it's react-native-webpack-server...

Do you do Slack or Gitter? I'd be cool to join a chatty roomy

**Comment by jhabdas** [comment]
I'll set up chat for the Kit. It's about that time.

**Comment by jhabdas** [comment]
See [`README.md`](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/README.md) for link to chatroom.

![just-add-gitter](https://cloud.githubusercontent.com/assets/440298/11708462/1cd144f4-9ed5-11e5-9699-c51a172cd7f5.jpeg)

**Comment by bendyorke** [comment]
Was there any solution found to this?  I'm experiencing the same issue.  I've tried multiple versions of node, npm, Xcode (including the @jhabdas's env linked above), npm cache cleans, computer restarts, removing derived data, all to no success.

**Comment by bendyorke** [comment]
To clarify, the issue I'm having is the `Incompatible block pointer types passing 'void (^)(RCTLogLevel...` error.  A temporary fix I found was just to comment out these lines:

```
RCTSetLogFunction(^(RCTLogLevel level, NSString *fileName, NSNumber *lineNumber, NSString *message) {
  if (level >= RCTLogLevelError) {
    redboxError = message;
  }
});
```

of the function `- (void)testRendersWelcomeScreen` in `App/AppTests/AppTests.m`.  It's not a fix by any means, but at least it get's me up and running until someone smarter than me can figure out the actual issue! :stuck_out_tongue:

**Comment by bendyorke** [comment]
Also, changing 
```
RCTSetLogFunction(^(RCTLogLevel level, NSString *fileName, NSNumber *lineNumber, NSString *message) {
```
of `- (void)testRendersWelcomeScreen` in `App/AppTests/AppTests.m` to 
```
RCTSetLogFunction(^(RCTLogLevel level, RCTLogSource source, NSString *fileName, NSNumber *lineNumber, NSString *message) {
```
Fixed the error.  To be honest I'm not sure which is a better solution.

**Comment by lynndylanhurley** [comment]
@bendyorke - I was able to get the app to build with your fix

**Comment by diffractometer** [comment]
@lynndylanhurley @bendyorke I was able to get the app to build with the fix.

**Comment by diffractometer** [comment]
All signs seem to be pointing to react-native-webpack-server. Does anyone have any input on that? 

@jhabdas now that Es6 + Babel come out of the box in react-native do you think there's an argument for dropping webpack?

**Comment by bendyorke** [comment]
For what it's worth, webpack makes it seemingly impossible to use images.  Everything Facebook recommends for loading images did not work.  I removed web pack, and everything they suggested loaded the image with any issues

**Comment by jhabdas** [comment]
Please see my Lumpen Radio app for a more complex example using images and
video.

**Comment by schinknbrot** [comment]
Had the same problem. fixed it by running `react-native upgrade`.

**Comment by jhabdas** [comment]
I'd be a liar if I told you guys advancing an app this early in the game didn't require some creative environment configuration to use with Webpack and Babel. In fact, I tried several different methods to use Webpack when I started and they were all equally hard save for React Native Webpack Server.

Doing a `react-native` init will request to replace `ios/App/AppDelegate.m`. If you do it please be aware of what's changing in that file because the steps in this app are custom to make it work with Webpack on port `8080`.

I did a fresh clone off `master` and hit the `RTCLogLevel` error described by @diffractometer. Rather than churn on this I'm going to wait give it some time for the downstream deps to bump for better support of `react-native@0.16`. Meanwhile, please utilize the fix proposed by @bendyorke to workaround the issue and consider using the [Gitter chatroom](gitter.im/jhabdas/react-native-webpack-starter-kit) to discuss. PRs are always welcome for those who find a robust fix in the interim.

Keeping this issue open for further investigation.

**Comment by diffractometer** [comment]
Cool thanks @jhabdas! I will see you the chatroom.

**Comment by jhabdas** [comment]
Would someone be so kind as to let me know if this error is still occurring after bumping to RN `0.17.0`? I've tagged a [new release to support it](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v0.17.0). Cheers!

**Comment by diffractometer** [comment]
Nope everything works! Woo!
