### ISSUE TITLE
Ipa Name

### ISSUE THREAD

**Issue by patrickhaug** [jhabdas/react-native-webpack-starter-kit#3]
How do I change the ipa Name ? It's always App. Thanks

**Comment by jhabdas** [comment]
Hi @patrickhaug. If you're looking to rename your app - and, as a result, the `ipa` file - there are [resources out there](http://stackoverflow.com/questions/24031576/what-is-the-best-method-to-rename-project-name-in-every-where-from-xcode-5#24032022) to help on SO. Typically this involves using Xcode to rename the project, but can be done more surgically [like I did for Lumpen Radio](https://github.com/jhabdas/lumpen-radio/commit/3c7f152057549af7b471b8c87d503316e58e76ab) if you really want to remove all references to the old project name.

Please feel free to update the repo Wiki if you find a good method you'd like to share with others. Thanks!
