### ISSUE TITLE
Application App has not been registered.

### ISSUE THREAD

**Issue by oliviertassinari** [jhabdas/react-native-webpack-starter-kit#30]
I get the following issue when testing on an Android emulator from the master branch:
```
Application App has not been registered.
This is either due to a require() error during initialization
or failure to call AppRegistry.registerComponent.
```
However, It's working fine on the iOS simulator.

Any idea?

**Comment by oliviertassinari** [comment]
Well, it's working on a real Android device. So it's I assumed it's not linked to this project.

**Comment by jhabdas** [comment]
There must've been a breaking change in Android during the [RN 0.17 release](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v0.17.0). I haven't had a chance to set-up my Android environment locally to validate upgrades yet, so any help you might be able to provide would be greatly appreciated.

I noticed RN started trying to build in more development automation tools during the last release, some of which I had to pull out [during the upgrade](https://github.com/jhabdas/react-native-webpack-starter-kit/commit/ee61a131ed09c5a0fa83f61c0fa3b50791cf4b9f) for iOS in order to prevent build failures in Xcode.

**Comment by jhabdas** [comment]
Glad you were able to resolve your issue. Please let me know if there's any room for improvement in the documentation.

**Comment by oliviertassinari** [comment]
> so any help you might be able to provide would be greatly appreciated

I'm pretty new to react-native, I have no idea where to start :grimacing: 
Thanks anyway! I'm gonna use this awesome starter-kit for the react-native version of https://github.com/callemall/material-ui :smile:

**Comment by jhabdas** [comment]
MUI support for RN sounds like a dream come true. Please let me know when you beta! I'd love to try it out and incorporate into my [Lumpen Radio](https://github.com/jhabdas/lumpen-radio) app and [link to you](habd.as/awesome-react-boilerplates/#react-native) from my blog. Good luck!

**Comment by oliviertassinari** [comment]
That is going to take some time. I'm gonna keep you up to date when it's beta :grin:.
Here is the very first piece https://github.com/callemall/material-ui/pull/2611.
The goal is to polyfill our browser version to a native one, so I may with using some component of https://github.com/callemall/material-ui/pull/2611 or https://github.com/xinthink/react-native-material-kit.
We will see.

**Comment by tuneZola** [comment]
I get this error when I already have a React Native node process running. Make sure you have all your terminals closed and run ps aux | grep 'node'. You should not see any thing from React native running. If you do, you can manually kill the processes and then start everything again. It should work then.

**Comment by mpemburn** [comment]
Killing all node processes solved this one for me.  Thanks!

**Comment by jhabdas** [comment]
On older versions of react this was the error message for https://github.com/jhabdas/react-native-webpack-starter-kit/issues/58

**Comment by EEmmanuel** [comment]
thanks ... Killing all node processes...

**Comment by Shoshin23** [comment]
For me the issue was the modulename I was using in the appRegistry.registercomponent method. Just giving an alternative to people who've tried the above.
