### ISSUE TITLE
Seeing EPEERINVALID during NPM install

### ISSUE THREAD

**Issue by thachp** [jhabdas/react-native-webpack-starter-kit#31]
Repro(s)

    git clone https://github.com/jhabdas/react-native-webpack-starter-kit.git react-native-kit && cd $_
    npm install 
    
Get the following errors in the terminal.

    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package react-native@0.17.0 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 0.15.0-rc

**Comment by thachp** [comment]
Seems like an issue with react-native-webpack-server.   I have submitted a similar issue at 

https://github.com/mjohnston/react-native-webpack-server/issues/147

**Comment by jhabdas** [comment]
Thanks for the issue @thachp. While RNWS [looks for a new maintainer](https://github.com/mjohnston/react-native-webpack-server/issues/143) I've decided to push ahead on this app. The errors you're seeing are expected per the [release notes for `v1.17.0`](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.17.0) and should not impact your ability to use the kit. I'll leave this issue open until the errors (NPM 2) and warnings (NPM 3) are cleaned up upstream.

**Comment by thachp** [comment]
Thanks for your help.
