### ISSUE TITLE
Cannot find entry file index.ios.js

### ISSUE THREAD

**Issue by thachp** [jhabdas/react-native-webpack-starter-kit#32]
This error occur on my first attempt to build / run the starter kit.

Repro(s)

    git clone https://github.com/jhabdas/react-native-webpack-starter-kit.git mobile && cd $_
    npm install # or simply npm i
    npm start

    Open ios/App.xcodeproj in Xcode, build and run the project.

Environment(s)

    npm Darwin 15.0.0
    npm argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm node v4.2.1
    npm npm  v2.14.7

![screen shot 2015-12-23 at 5 01 29 pm](https://cloud.githubusercontent.com/assets/1495371/11987594/e8132012-a996-11e5-9173-d325fa5d5424.png)

**Comment by thachp** [comment]
It started working after I made small changes to the <text> component in App.js. Could it be that index.ios.js did not generate initially?  I don't see ios.index.js anywhere in the root directory.

**Comment by jhabdas** [comment]
Sorry to hear you're having issues getting set-up @thachp. But you're almost there! I used `nvm` to `install v4.2.1` and then did a `npm i -g npm@2.14.7` to get your version of NPM and, after a fresh clone from `master` see the following:

![screen shot 2015-12-23 at 7 32 51 pm](https://cloud.githubusercontent.com/assets/440298/11987870/83c0c126-a9ac-11e5-9275-5482a0a10c03.png)

Try taking a spin through the the [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html) guide for RN again please let us know how it goes!

**Comment by jhabdas** [comment]
Superb. Glad to hear you got it working. I dropped some knowledge in the README to help you get through from here to the App Store. Best of luck!
