### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by Hyperonic** [jhabdas/react-native-webpack-starter-kit#33]
After cloning and npm install I get the following on Android.

Invariant Violation. Application App has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent

**Comment by jhabdas** [comment]
Have you tried running on a device?

**Comment by jhabdas** [comment]
https://github.com/jhabdas/react-native-webpack-starter-kit/issues/30

**Comment by Hyperonic** [comment]
yes, running on device

**Comment by Hyperonic** [comment]
also tried replacing content of src/main.android.js with the default index.android.js content but still get the same error

**Comment by Hyperonic** [comment]
sorry. changed port from 8081 to 8080 and now it works

**Comment by mohamedpsx** [comment]
@Hyperonic where did you change the port ? and did you get it to work on emulator ? i am having the same issue here

**Comment by Hyperonic** [comment]
@mohamedpsx inside app open Dev Settings then open the very last item. enter your connected working machine(laptop) ip address followed by colon and port 8081. then reload js

**Comment by mohamedpsx** [comment]
@Hyperonic Thank you :D it is working now, and seems that the issue is within react native it self, did you write an issue there ?

**Comment by jhabdas** [comment]
Would love to hear feedback on the usefulness/discoverability of the following `npm run` script:

https://github.com/jhabdas/react-native-webpack-starter-kit/blob/f07854b2f75f0ae6aed2b8297a983a55e6d91ed0/package.json#L8

**Comment by mohamedpsx** [comment]
same error running with or without that npm run script, but i run react-native android as in the official doc instead of react-native run-android and it works out of the box no need for the android-setup-port, i think it runs a reverse connection by default when running react-native android.

I am no android expert, but this is what i tried and it seems to work, we can investigate more if you want

**Comment by jhabdas** [comment]
:+1:
