### ISSUE TITLE
Integrate react-redux/native

### ISSUE THREAD

**Issue by thachp** [jhabdas/react-native-webpack-starter-kit#34]
Thoughts on including react-redux/native as part of the starer kit? 

https://github.com/rackt/react-redux

**Comment by jhabdas** [comment]
Thanks for the request, @thachp. My plan is to keep this kit as light-weight as possible so it benefits a larger audience and helps enable me to keep it sliding forward on the latest RN stable release. I left a link in the `README` pointing to [some other kits](http://habd.as/awesome-react-boilerplates/#react-native) (some of which include Redux).

I'd love to see a fork open sourced with Redux, Testing and Exponent added in (as well as one for Relay). But sometimes it's easier to build from scratch so you can grok everything that's happening. Unfortunately that also means some individuals won't bake in support for ES6/ES7 early on although I feel everyone should.
