### ISSUE TITLE
Build failing for android emulator

### ISSUE THREAD

**Issue by mohamedpsx** [jhabdas/react-native-webpack-starter-kit#35]
Hey, i am unable to run a fresh install on android emulator but it does run on device as in #33 so any idea on how to fix this or what is the source of the issue ? and also i wanted to ask about your plan for rnws that is not actively maintained ? 

thanks!

**Comment by jhabdas** [comment]
Happy New Year. RNWS is growing into 2016. I know the app works on a mobile
device. If you have a contribution to make Android better I would love to
merge it.

**Comment by jhabdas** [comment]
@mohamedpsx Can you confirm Android emulator works with updated port settings as discussed in https://github.com/jhabdas/react-native-webpack-starter-kit/issues/33?

**Comment by mohamedpsx** [comment]
Yep, confirmed and it is not an issue related to this project, Thank's :dancer:

**Comment by jhabdas** [comment]
:balloon:
