### ISSUE TITLE
Cannot start bundled iOs application

### ISSUE THREAD

**Issue by michalpetrov** [jhabdas/react-native-webpack-starter-kit#38]
I have done following:
1. clone
2. npm i
3. npm start
4. open xcode a started app in simulator 
Application started

Then i wanted to test the bundling, so i have done folowing:
1. uncommented option 2 (jsCodeLocation) in AppDelegate.m
2. npm run bundle
3. started the application in simulator again
This errors were logged in xcode console and application:
[warn][tid:com.facebook.React.JavaScript] Requiring unknown module "react-native-webpack-server/_entry/index.ios.js"
[error][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Requiring unknown module "react-native-webpack-server/_entry/index.ios.js"
[error][tid:main] ReferenceError: Can't find variable: __DEV__

**Comment by jhabdas** [comment]
Almost there. Looks like the NPM dependencies didn't finish installing. To inspect the status of your dependencies run `npm ls` at the bash prompt and look for errors related to missing packages. You can run `npm i` again to finish the installaiton, though I often find it faster to simply run `npm up` to nudge the NPM dependency manager to install any missing dependencies.

**Comment by michalpetrov** [comment]
Thanks for  quick reply.
That helped to solve the problem with unknown module, but I still have the following error:
ReferenceError: Can't find variable: __DEV__

**Comment by jhabdas** [comment]
It's in there. Try `rm -rf node_modules` and reinstalling dependencies fresh. If that doesn't work please reply with the output from `npm -v && node -v`.

**Comment by michalpetrov** [comment]
It didn't help.
npm: 3.3.12
node: v5.1.1

**Comment by jhabdas** [comment]
Sorry you're having environment issues. Both `npm` 3 and Node 5 are a bit experimental. For a more stable environment try [following along with this example](https://github.com/jhabdas/react-native-webpack-starter-kit/issues/13#issuecomment-161868142).

**Comment by michalpetrov** [comment]
I've have installed node v4.2.4 and npm 2.14.12, deleted node_modules, reinstalled dependencies, rebuild bundle but still getting the same error

**Comment by jhabdas** [comment]
Have you run through the RN environment set-up instructions again? I left a
link to their instructions below the screenshot of the running simulator in
the previously linked post. That's all the help I can offer here,
unfortunately.

**Comment by michalpetrov** [comment]
I tried again on a clean enviroment (El Capitan).
Installed everything according react-native "Getting started".
Generate empty application (AwesomeProject), uncommented local bundle loading in AppDelegate.m and everything has run as expected.
Then I cloned this repo, run `npm i`, `npm up`, `npm start` .... run application in simulator ... OK.
Then `npm run bundle`, edited AppDelegate.m, started in simulator and again the same error.

I noticed that AppDelegate.m in this repo is different (older) than the one created by `react-native init`. May it be version 0.17 vs 0.18 ?

**Comment by jhabdas** [comment]
It is 17. And its modified to pull some RN build stuff. Please hit the chat
room linked from the README if you can. Looks like someone else is having
difficulty too, and just opened another environment issue. Please let us
know what you find out.

**Comment by hugocaillard** [comment]
Indeed `$ npm run bundle` seems to fail at creating a valid bundle.
You can do it "manually" by running `$ npm start`, when the server is ready run `$ curl "http://localhost:8080/index.ios.bundle?platform=ios&dev=true" -o ios/main.jsbundle`, which will get you a valid bundle. Then you'll be able to install it on a device.

It should also be quite easy to get a minified version and a non-dev version, but it seems to bring some issues with the bundling script (and the `undefined __DEV__` error).

**Comment by jhabdas** [comment]
That sounds right. Will plan to update README if no one else gets to it
first. Above instructions also found inside the app source. Just search 8080

**Comment by hugocaillard** [comment]
Yes I simply took it from AppDelegate.m. But I didn't figure out yet how to get a working "production ready" bundle, as we should get with `$ npm run bundle`.

**Comment by jhabdas** [comment]
I've been creating my distributable bundles using cURL. See README link for
App Store submission tips.

**Comment by jhabdas** [comment]
Stale
