### ISSUE TITLE
Unable to Start iOS Application Development Server

### ISSUE THREAD

**Issue by davidseik** [jhabdas/react-native-webpack-starter-kit#39]
Hi, I Cloned the Repo and followed the steps to install all node_modules (Without any issues). After that I do the following Steps
`npm start (starts the server and should start the webpack bundler)`

And then I go to the XCode Project and Hit Run; That opens a new terminal window with the facebook packager; No Mistakes so far, however, in the first window it appears that Webpack spits the output and then
...
webpack: bundle is now VALID.

react-native packager ready...

undefined

`{"message":"Cannot find entry file index.ios.js in any of the roots: 
[\"/Users/xxx/Documents/Dev/react-native-
kit\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}`

Seems like webpack is not generating the bundle correctly because of some sort of collision between server ports, I get another error in the other window:
`ERROR  Packager can't listen on port 8081
Most likely another process is already using this port
Run the following command to find out which process:
   lsof -n -i4TCP:8081 `

**Comment by jhabdas** [comment]
Sorry you're having trouble getting the app running on your machine. I'm working on some other stuff at the moment and can't help debug at the moment. Please feel free to take to the chatroom. I left a link in the `README`. Good luck!

**Comment by hugocaillard** [comment]
@davidseik I had the same problem, just wait (quite a long time) after `$npm start`, it should start the Packager on the port 8081. (It really can be pretty long.)
After that, it will not open a new terminal window when you'll hit run.

**Comment by jhabdas** [comment]
Thanks for the info, @hugocaillard!
