### ISSUE TITLE
upgrading to RN to 0.18.0 

### ISSUE THREAD

**Issue by elliott-vorel** [jhabdas/react-native-webpack-starter-kit#43]
Getting this error:
undefined is not an object (evaluating 'process.env.NODE_ENV')

Any idea what the problem could be. Possibly related to webpack?

**Comment by jhabdas** [comment]
Please see #41 and #42. I'm considering skipping 0.18 altogether depending on how the move to 0.19 goes.

**Comment by jhabdas** [comment]
As promised https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.19.0
