### ISSUE TITLE
webpack server crashes on Windows

### ISSUE THREAD

**Issue by ask10000** [jhabdas/react-native-webpack-starter-kit#46]
After running `npm start` I see some errors related to linebreak rules of eslint - CRLF instead of LF - and after that it says bundle is valid (though not sure if bundle is really valid). When I try to access the bundle url - http://localhost:8080/index.android.bundle , this is what I see - 

`ERROR  Watcher took too long to load (NodeWatcher)
Error: Watcher took too long to load (NodeWatcher)
    at [object Object]._onTimeout (index.js:99:16)
    at Timer.listOnTimeout (timers.js:92:15)`

`See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
undefined
Cannot GET /undefined.js`

`events.js:141
      throw er; // Unhandled 'error' event
      ^`

`Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)`

`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ask10000\\softwares\\nodejs\\node.exe" "C:\\Users\\ask10000\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"`
`npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! App@1.17.0 start: `rnws start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App@1.17.0 start script 'rnws start'.
npm ERR! This is most likely a problem with the App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rnws start
npm ERR! You can get their info via:
npm ERR!     npm owner ls App
npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:
npm ERR!     D:\Apps\react-native-webpack-starter-kit\react-native-kit\npm-debug.log`

**Comment by ask10000** [comment]
Prior to this error, I got this on my console..

`D:\Apps\react-native-webpack-starter-kit\react-native-kit>npm start

> App@1.17.0 start D:\Apps\react-native-webpack-starter-kit\react-native-kit
> rnws start

Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: 8e05cd0b77c77f93eaa8
Version: webpack 1.12.13
Time: 21803ms
               Asset     Size  Chunks             Chunk Names
    index.android.js    11 kB       0  [emitted]  index.android
        index.ios.js    11 kB       1  [emitted]  index.ios
index.android.js.map  4.71 kB       0  [emitted]  index.android
    index.ios.js.map  4.68 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 8.91 kB [rendered]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 8.91 kB [rendered]

ERROR in ./src/main.ios.js

D:\Apps\react-native-webpack-starter-kit\react-native-kit\src\main.ios.js
   1:4   error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   2:36  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   3:63  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   4:4   error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   5:42  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   6:36  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   7:1   error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   8:25  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
   9:25  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
  10:3   error  Expected indentation of 2 space characters but found 0  indent
  10:23  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
  11:3   error  Expected indentation of 2 space characters but found 0  indent
  11:71  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
  12:4   error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
  13:2   error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style
  14:50  error  Expected linebreaks to be 'LF' but found 'CRLF'         linebreak-style

? 16 problems (16 errors, 0 warnings)


ERROR in ./src/main.android.js

D:\Apps\react-native-webpack-starter-kit\react-native-kit\src\main.android.js
   1:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:63  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:42  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:61  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:2   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:50  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

? 14 problems (14 errors, 0 warnings)


ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module parse failed: D:\Apps\react-native-webpack-starter-kit\react-native-kit\node_modules\react-native\Libraries\react-native\react-native.js L
You may need an appropriate loader to handle this file type.
|   // Note: this must be placed last to prevent eager
|   // evaluation of the getter-wrapped submodules above
|   ...require('React'),
| };
|
 @ ./src/main.ios.js 5:19-42

ERROR in ./src/components/App.js

D:\Apps\react-native-webpack-starter-kit\react-native-kit\src\components\App.js
   1:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:63  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:58  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:54  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  24:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  25:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  26:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  27:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  33:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:41  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  36:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  37:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  38:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  39:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  42:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  43:51  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  44:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  45:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  46:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  47:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  48:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  49:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  50:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  51:2   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  52:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  53:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  54:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  55:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  56:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  57:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  58:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  59:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  60:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  61:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  62:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  63:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  64:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  65:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  66:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  67:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  68:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  69:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  70:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  71:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  72:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

? 72 problems (72 errors, 0 warnings)

webpack: bundle is now VALID.
react-native packager ready...
 +----------------------------------------------------------------------------+
 ¦  Running packager on port 8081.                                            ¦
 ¦                                                                            ¦
 ¦  Keep this packager running while developing on any JS projects. Feel      ¦
 ¦  free to close this tab and run your own packager instance if you          ¦
 ¦  prefer.                                                                   ¦
 ¦                                                                            ¦
 ¦  https://github.com/facebook/react-native                                  ¦
 ¦                                                                            ¦
 +----------------------------------------------------------------------------+
Looking for JS files in
   D:\Apps\react-native-webpack-starter-kit\react-native-kit
   D:\Apps\react-native-webpack-starter-kit\react-native-kit\node_modules\react-native-webpack-server\_entry

[11:23:01 AM] <START> Building Dependency Graph
[11:23:01 AM] <START> Crawling File System
[11:23:01 AM] <START> Loading bundles layout
[11:23:01 AM] <END>   Loading bundles layout (1ms)
[Hot Module Replacement] Server listening on /hot

React packager ready.

 ERROR  Watcher took too long to load (NodeWatcher)
Error: Watcher took too long to load (NodeWatcher)
    at [object Object]._onTimeout (index.js:99:16)
    at Timer.listOnTimeout (timers.js:92:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.`

**Comment by jhabdas** [comment]
Can you confirm you're able to start another React Native project, and one
using Webpack? Have you tried running under Docker?

**Comment by jhabdas** [comment]
Also, do you have EditorConfig enabled? It's configured to handle line
feeds across platforms.

**Comment by ask10000** [comment]
Initially I didnt. But after your last comment, I enabled editorconfig to sublime and opened and saved the files causing issues. Those are clear now. But the issue with crash still goes on. Here is the log - 


`D:\Apps\react-native-webpack-starter-kit\react-native-kit>npm start`

&gt; App@1.17.0 start D:\Apps\react-native-webpack-starter-kit\react-native-kit
&gt; rnws start
`
Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: d43abcbf30f6ec9f4349
Version: webpack 1.12.13
Time: 14456ms
               Asset     Size  Chunks             Chunk Names
    index.android.js    11 kB       0  [emitted]  index.android
        index.ios.js    11 kB       1  [emitted]  index.ios
index.android.js.map  4.54 kB       0  [emitted]  index.android
    index.ios.js.map  4.52 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 8.9 kB [rendered]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 8.91 kB [rendered]

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module parse failed: D:\Apps\react-native-webpack-starter-kit\react-native-kit\node_modules\react-native\Libraries\react-native\react-native.js Line 114: Unexpected token ...
You may need an appropriate loader to handle this file type.`
`
|   // Note: this must be placed last to prevent eager
|   // evaluation of the getter-wrapped submodules above
|   ...require('React'),
| };
|
 @ ./src/main.ios.js 5:19-42
webpack: bundle is now VALID.
react-native packager ready...
 +----------------------------------------------------------------------------+
 ¦  Running packager on port 8081.                                            ¦
 ¦                                                                            ¦
 ¦  Keep this packager running while developing on any JS projects. Feel      ¦
 ¦  free to close this tab and run your own packager instance if you          ¦
 ¦  prefer.                                                                   ¦
 ¦                                                                            ¦
 ¦  https://github.com/facebook/react-native                                  ¦
 ¦                                                                            ¦
 +----------------------------------------------------------------------------+
Looking for JS files in
   D:\Apps\react-native-webpack-starter-kit\react-native-kit
   D:\Apps\react-native-webpack-starter-kit\react-native-kit\node_modules\react-native-webpack-server\_entry

[12:53:48 PM] <START> Building Dependency Graph
[12:53:48 PM] <START> Crawling File System
[12:53:48 PM] <START> Loading bundles layout
[12:53:48 PM] <END>   Loading bundles layout (3ms)
[Hot Module Replacement] Server listening on /hot

React packager ready.

undefined
Cannot GET /undefined.js
`
`events.js:141
      throw er; // Unhandled 'error' event
      ^
`
`
Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ask10000\\softwares\\nodejs\\node.exe" "C:\\Users\\ask10000\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! App@1.17.0 start: `rnws start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App@1.17.0 start script 'rnws start'.
npm ERR! This is most likely a problem with the App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rnws start
npm ERR! You can get their info via:
npm ERR!     npm owner ls App
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Apps\react-native-webpack-starter-kit\react-native-kit\npm-debug.log

D:\Apps\react-native-webpack-starter-kit\react-native-kit>`

**Comment by jhabdas** [comment]
The last issue you commented on is occurring because `react-native` is using rest spread. I left a link with more details here: https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.17.0. 

Does your Webpack config have the following loader which ships with this kit? https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/webpack.config.js#L31-L39

**Comment by ask10000** [comment]
Yes, the webpack config has that loader u pointed as I didnt change what came with the kit. Not sure why this ECONNRESET happens. May be it has nothing to do with RNWS, may be something to do with webpack itself. But then there are other webpack projects on my system which run ok.

**Comment by jhabdas** [comment]
What versions of NPM and node are you using on your Windows machine?

**Comment by ask10000** [comment]
npm @ 2.14.7
node @ v4.2.1

**Comment by jhabdas** [comment]
After debugging your original problem, the issue seems to be now with the
loader for the RN dep as I pointed out earlier. What happens if you make
that loader a pre-loader? Also, what happens if you reinstall dependencies
using NPM3? These steps should help debug.

**Comment by deanshub** [comment]
@ask10000 
Iv'e managed to fix this by enabling EditorConfig on my atom editor then saving 
App.js., main.android.js, main.ios.js files
and changing in the webpack.config.js file
this line:
```include: /node_modules\/react-native/,```
into this line
```include: /node_modules\\react-native/,```

**Comment by jhabdas** [comment]
@deanshub I released a new version of this starter kit today with updated dependencies. Please upgrade to [the latest version](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.20.0) and open a new issue if you continue to have problems after upgrading.
