### ISSUE TITLE
ECONNRESET crash on Windows 7, npm 3.6.0, node v5.6.0

### ISSUE THREAD

**Issue by ask10000** [jhabdas/react-native-webpack-starter-kit#55]
This is reopening of issue #46 
After @deanshub 's comment for changes in `App.js`, `main.android.js` and `main.ios.js` on after enabling editorconfig on Sublime, webpack.config.js loaded entry change from 
`include: /node_modules\/react-native/,` to `include: /node_modules\\react-native/,`, rnws started properly.

However, as soon as app is started, rnws server crashes with ECONNRESET error. Attaching npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\ask10000\\softwares\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ask10000\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle App@0.1.0~prestart: App@0.1.0
6 silly lifecycle App@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle App@0.1.0~start: App@0.1.0
8 verbose lifecycle App@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle App@0.1.0~start: PATH: C:\Users\ask10000\softwares\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Apps\ReactNativeLab\rnws\react-native-kit\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\CheckPoint\File Encryption\Program\;C:\Java\jdk1.8.0_66\bin;C:\Users\ask10000\softwares\grails-3.0.10\grails-3.0.10\bin;C:\Users\ask10000\softwares\curl-7.43.0-win64\bin;C:\Users\ask10000\softwares\Git\cmd;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\ask10000\softwares\Python27;C:\Users\ask10000\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\ask10000\softwares\nodejs\;C:\Users\ask10000\AppData\Local\atom\bin;C:\Users\ask10000\softwares\Scite;C:\Users\ask10000\softwares\SublimeText3;C:\Users\ask10000\AppData\Local\Android\sdk\platform-tools;C:\Users\ask10000\AppData\Local\Android\sdk\tools;C:\Users\ask10000\AppData\Roaming\npm
10 verbose lifecycle App@0.1.0~start: CWD: D:\Apps\ReactNativeLab\rnws\react-native-kit
11 silly lifecycle App@0.1.0~start: Args: [ '/d /s /c', 'rnws start' ]
12 silly lifecycle App@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle App@0.1.0~start: Failed to exec start script
14 verbose stack Error: App@0.1.0 start: `rnws start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\ask10000\softwares\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\ask10000\softwares\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid App@0.1.0
16 verbose cwd D:\Apps\ReactNativeLab\rnws\react-native-kit
17 error Windows_NT 6.1.7601
18 error argv "C:\\Users\\ask10000\\softwares\\nodejs\\node.exe" "C:\\Users\\ask10000\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error App@0.1.0 start: `rnws start`
22 error Exit status 1
23 error Failed at the App@0.1.0 start script 'rnws start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the App package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rnws start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs App
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls App
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ask10000** [comment]
Requested URL http://localhost:8080/index.android.bundle from browser and found the same issue.

**Comment by ask10000** [comment]
The console log - 

D:\Apps\ReactNativeLab\rnws\react-native-kit>npm start

> App@0.1.0 start D:\Apps\ReactNativeLab\rnws\react-native-kit
> rnws start

Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: 063de06d8e9259b0ac10
Version: webpack 1.12.14
Time: 5951ms
               Asset     Size  Chunks             Chunk Names
    index.android.js    24 kB       0  [emitted]  index.android
        index.ios.js  24.1 kB       1  [emitted]  index.ios
index.android.js.map  35.2 kB       0  [emitted]  index.android
    index.ios.js.map  36.5 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 17 kB [rende
red]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 17 kB [rendered]
webpack: bundle is now VALID.
react-native packager ready...
 ┌────────────────────────────────────────────────────────────────────────────┐

 │  Running packager on port 8081.                                            │

 │                                                                            │

 │  Keep this packager running while developing on any JS projects. Feel      │

 │  free to close this tab and run your own packager instance if you          │

 │  prefer.                                                                   │

 │                                                                            │

 │  https://github.com/facebook/react-native                                  │

 │                                                                            │

 └────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   D:\Apps\ReactNativeLab\rnws\react-native-kit
   D:\Apps\ReactNativeLab\rnws\react-native-kit\node_modules\react-native-webpac
k-server\_entry

[4:05:35 PM] <START> Building Dependency Graph
[4:05:35 PM] <START> Crawling File System
[4:05:35 PM] <START> Loading bundles layout
[4:05:35 PM] <END>   Loading bundles layout (15ms)
[Hot Module Replacement] Server listening on /hot

React packager ready.

[4:06:57 PM] <END>   Crawling File System (82784ms)
[4:06:57 PM] <START> Building in-memory fs for JavaScript
[4:06:58 PM] <END>   Building in-memory fs for JavaScript (685ms)
[4:06:58 PM] <START> Building in-memory fs for Assets
[4:06:59 PM] <END>   Building in-memory fs for Assets (675ms)
[4:06:59 PM] <START> Building Haste Map
[4:06:59 PM] <START> Building (deprecated) Asset Map
[4:06:59 PM] <END>   Building (deprecated) Asset Map (129ms)
[4:06:59 PM] <END>   Building Haste Map (398ms)
[4:06:59 PM] <END>   Building Dependency Graph (84555ms)
undefined
Cannot GET /undefined.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:546:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ask10000\\softwares\\nodejs\\node.exe" "C:\\Users\\a
sk10000\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! App@0.1.0 start: `rnws start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App@0.1.0 start script 'rnws start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rnws start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs App
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls App
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Apps\ReactNativeLab\rnws\react-native-kit\npm-debug.log

**Comment by jhabdas** [comment]
@ask10000 thanks for reopening given you're still having problems. I used to work on a Windows machine as well and have traditionally had difficulty running Node projects on that platform. So much so, in fact, that I had to use virtualization on Windows just to [Develop Single Page Apps on Windows](http://habd.as/developing-modern-web-applications-on-windows-vagrant/).

Looking over the build output it looks like things go awry while RN builds the dependency graph, a tricky part of the system I even struggled with on OS X early on while building [Lumpen Radio](https://github.com/jhabdas/lumpen-radio).

I have access to Window machines and can try to recreate as early as this weekend. Meanwhile, would you be able to try running the Example Babel project in the [`react-native-webpack-server`](https://github.com/mjohnston/react-native-webpack-server) repo and let me know if it works. That'll help narrow down the problem before I dust off the old machine and start looking for cables.

**Comment by ask10000** [comment]
Thanks @jhabdas . I will give react-native-webpack-server a try. But just last week I had tried to install it but ran into some problem of UNMET PEER DEPENDENCY where installation had failed to install react-native@>=0.13.0, webpack@>=1.8.4 and webpack-dev-server@>1.8.0. I am new to this but i suppose i have to globally install these specific versions of react-native, webpack and webpack-dev-server for rnws to get installed properly. Correct?

**Comment by jhabdas** [comment]
@ask10000 specifically I would try to get their Babel example running (from the Examples directory in that repo). If you do, and receive the same errors you did here, you're one step closer to isolating the root cause.

**Comment by jhabdas** [comment]
@ask10000 According to the official React Native documentation at least, OS X is required for development. But I don't like people telling me no so I went ahead and created a custom virtual environment running this kit on Linux with Docker for use on Windows anyway.

Please see the updated [Installation instructions](https://github.com/jhabdas/react-native-webpack-starter-kit#installation).

This would make you one of the first Windows users capable of building React Native apps. I'd appreciate any feedback you could give once you get set-up if you're ready to take next steps.

**Comment by ask10000** [comment]
Thanks @jhabdas . Appreciate your efforts to get us Windows suckers like us on react-native. Unfortunately this is a company IT issued machine and current IT policies don't allow VirtualBox or similar virtualization tools to be installed on these machines. But I am going to try this route using another Windows machine - just to validate this approach works too. Thanks again.

**Comment by jhabdas** [comment]
Thanks. I've used a similar approach [in the past](http://habd.as/developing-modern-web-applications-on-windows-vagrant/) to build complex Node apps on Windows and 'm confident in the mechanics of the approach. Feel free to dump any feedback here (over chat) for better visibility.
