### ISSUE TITLE
node module "react-deep-force-update" dependent on babel5

### ISSUE THREAD

**Issue by flappymonkey** [jhabdas/react-native-webpack-starter-kit#57]
TransformError: /Volumes/data/git/react-native_sets/react-native-webpack-starter-kit/node_modules/react-deep-force-update/lib/index.js: [BABEL] /Volumes/data/git/react-native_sets/react-native-webpack-starter-kit/node_modules/react-deep-force-update/lib/index.js: Unknown option: /Volumes/data/git/react-native_sets/react-native-webpack-starter-kit/node_modules/react-deep-force-update/.babelrc.stage

**Comment by flappymonkey** [comment]
you can do this to handle babel6 problem
"scripts": {
  "clean:babelrc": "find ./node_modules -name react-packager -prune -o -name '.babelrc' -print | xargs rm -f",
  "postinstall": "npm run clean:babelrc"
}

**Comment by jhabdas** [comment]
Babel strikes again. Thanks for the workaround. Will take a closer look this weekend while making updates to the kit.

**Comment by jhabdas** [comment]
@flappymonkey Could you provide some context into what caused this error, and how it relates to this starter kit?

**Comment by jhabdas** [comment]
Closing this as we've got the information provided. If you feel this issue may be affecting others please let us know how to reproduce it by providing information about your environment including kit version used and your `node -v && npm -v` and re-open when we see at least one more report.
