### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by ccorcos** [jhabdas/react-native-webpack-starter-kit#62]
Why not add HMR to this repo?

https://github.com/gaearon/react-transform-hmr#react-native

**Comment by jhabdas** [comment]
To spare headaches and developer frustration I porposely omitted it from this kit. While it looks great on paper, the actual development workflow hurts the ability to use source maps for step debugging and generally leads to a cool, but less effective, developer experience. The RWNS dev dependency has partial support, if that's your thing. You'd have to hook it up based on their examples. But you'll find during dev most of your time is spent compiling anyways - and there's nothing HMR can do to help you there.
