### ISSUE TITLE
/bin/sh: 1: VOLUME: not found

### ISSUE THREAD

**Issue by outdooricon** [jhabdas/react-native-webpack-starter-kit#63]
I'm running your windows docker setup `docker build --rm .` and it ends after a lot of runtime with this final output:

```
...
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/pywatchman-1.3.0-py2.7.egg-info
/usr/bin/install -c -d -m 777 //usr/local/var/run/watchman
chmod g+s //usr/local/var/run/watchman
touch //usr/local/var/run/watchman/.not-empty
 /bin/mkdir -p '//usr/local/share/doc/watchman-4.5.0'
 /usr/bin/install -c -m 644 README.markdown '//usr/local/share/doc/watchman-4.5.0'
make[1]: Leaving directory '/tmp/watchman'
/bin/sh: 1: VOLUME: not found
The command '/bin/sh -c apt-get update && apt-get install -y python-dev &&   mkdir -p /tmp/watchman &&   wget https://github.com/facebook/watchman/archive/$WATCHMAN_VERS.tar.gz &&   tar --strip-components=1 -xzf $WATCHMAN_VERS.tar.gz -C /tmp/watchman &&   cd /tmp/watchman &&   ./autogen.sh && ./configure && make && make install &&   rm -f $WATCHMAN_VERS.tar.gz && VOLUME /app' returned a non-zero code: 127

```

**Comment by outdooricon** [comment]
not sure if it's related, but higher in the output i see a few of:

```
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
```

**Comment by jhabdas** [comment]
Thanks for the report @outdooricon. Windows support is very new, and the path forward isn't entirely clear. But my vision here is to allow RN development using CoreOS in the next six months. Thanks for braving your way into these waters.

What happens when you remove the [`VOLUME` line](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/abadf986a1d72af2cb7c7341f48f7cec3cb6259d/Dockerfile#L41) from the `Dockerfile` and rebuild the image?

**Comment by jhabdas** [comment]
@outdooricon I just landed https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v2.20.2 which may help fix your problem. You'll need to rebuild your Docker image after cloning or updating to the new version. Please give it a shot and let me know how it goes.

**Comment by outdooricon** [comment]
pulling... will update soon!

**Comment by jhabdas** [comment]
Thanks @outdooricon. Basically what I did was try to limit the files mounted between operating systems to only the files in the `src` directory. This was an approach I had success with [while building virtualized Node apps on Windows](http://habd.as/developing-modern-web-applications-on-windows-vagrant/) in the past.

**Comment by jhabdas** [comment]
@outdooricon Oops. I forgot the fabric softener! We need to update `KIT_VERS` in the `Dockerfile` to pull the updated kit version. You can do this locally. I'm going to push a new release up meanwhile. You'll see a [deep dependency error](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v2.20.1) I put a workaround in earlier if you do not.

**Comment by outdooricon** [comment]
haha, yes i had to address this one earlier and was going to comment on it next. I just had a successful build of the docker container build this time around, so your change for watchman worked!

**Comment by jhabdas** [comment]
Superb. I released [another version](https://github.com/jhabdas/react-native-webpack-starter-kit/tree/v2.20.4) to tackle the ESLint issue for Docker users. I'm going to close this now. If you continue to have issues please open a new ticket. Either way I'd love to hear about your experiences, and any tips you come up with in this thread or in the Gitter chatroom linked from the `README`. Cheers.

**Comment by outdooricon** [comment]
@jhabdas now that I've got the docker container going, I'm realizing that I'm not entirely sure of the workflow (this is my first foray into docker). I'm seeing that changes I make on my local clone aren't being reflected into the docker container. Also builds from the docker container aren't being transferred out into my local, so what is the workflow that you use with it?

**Comment by jhabdas** [comment]
@outdooricon I saw your note in Gitter. Sorry for not replying yet as I try to keep kit updates as a weekend activity.

The next steps are to get Watchman running responsively and without error. Then there are two paths forward I can see:

- Enable updates from Docker host operating system to be recognized by `react-native-webpack-starter-kit` and `watchman` (one or both, as necessary). I've done this with Vagrant in the past [as described here](http://habd.as/developing-modern-web-applications-on-windows-vagrant/#move-the-web-root-outside-of-vagrant-synced-folders).
- Develop inside the docker container until proper file system syncing is installed

To actually see and test changes we'll need to find an integration with something like Exponent, as described in the [updated Docker `README` instructions](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/v2.21.0/README.md#using-with-docker). Thanks for being a part of this experiment to bring RN development to the likes of Raspberry Pi (and [the people who'll use it](https://www.raspberrypi.org/about/)).

**Comment by outdooricon** [comment]
Ah ok, sorry to double post. Fwiw, I was able to get the container to see my host files by commenting out your volume set in the dockerfile and then using this cmd to run: 
```
docker run -v /c/Users/[username]/[cloneLocation]/src:/app/src 
                  -v /c/Users/[username]/[cloneLocation]/build:/app/build 
                  -it [imageId] /bin/bash
```

This puts me at the point that I think is ideal, where I can do local dev and have the docker build off of that and into a hosts directory (once watchman works). I am seeing though that the build directory doesn't get used... it looks like `npm run build` dumps right into the base app dir, which I can't use as a mounted folder. Also,I'm not entirely sure how to point the emulator to rnws in the docker container (this is probably my own ignorance of docker currently).

Thanks for working on this! I'm happy to be a part of it, for my own selfish reasons of

**Comment by jhabdas** [comment]
This is extremely useful info. Please keep it coming. Meanwhile I'll continue to look for ways to adjust the codebase. I understand it's a little magical, but it sounds like you're picking it up very quickly.

The React Native Webpack Server I'm building on I've forked before and will do again, if necessary, to achieve more broad support for RN development.

RNWS defaults output to, I believe, the "_entry" directory under its "./node_module" directory. But the code is generated on the fly so we're not polluting the repo with generated source. IOW, I think my Webpack config may be misleading. But this may need to be confirmed.

I'm traveling next week but will try and put in a few hours this weekend using what info you can provide, and blockers you face.

**Comment by jhabdas** [comment]
If you want to generate a bundle, I left a cURL statement example in AppDelegate.m you can use to do so. It's how I produced the bundle I upload with the iOS app I built and later pulled this kit from.

**Comment by jhabdas** [comment]
There's also and NPM command to run the bundle but I'm not sure if it took any collateral damage as I've been pushing the primary RN dependency forward.
