### ISSUE TITLE
how can i test in my real iphone

### ISSUE THREAD

**Issue by lucianlo** [jhabdas/react-native-webpack-starter-kit#69]
@jhabdas 

Bundling

## Bundling

Building the app for distribution.

1. Execute `npm run bundle` to generate the [offline JS bundle](https://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle).
1. For iOS, update `AppDelegate.m` to load from pre-bundled file on disk.
1. Test the application, create an archive and submit to the store.

saying that:

> 
unable to execute js call: fbBatchedBridge is undefined

then how can i test in my real iphone?thx

**Comment by jhabdas** [comment]
Please skip Step 1 and use the cURL statement pointed at in Step 2. I'll leave this open until I rewrite the bundle step as a script to run the cURL statement mentioned. If you run into any problems, please let me know.

Also, I left some links to articles I wrote in the README to help you get to the Store with React Native.

**Comment by jhabdas** [comment]
@lucianlo I ran the bundle step without issue, so there may be an issue in your environment. If you continue to experience problems please consider opening an issue against [`react-native-webpack-server`](https://github.com/mjohnston/react-native-webpack-server) as I'm calling its bundle step directly in my `bundle` script housed in `package.json` by calling `rwns bundle` (which runs the `rwns` binary in `./node_modules/.bin/` following an `npm install`. Thanks and good luck!
