### ISSUE TITLE
[MacOS] Enable Live Reload not triggering refresh

### ISSUE THREAD

**Issue by seanfuture** [jhabdas/react-native-webpack-starter-kit#73]
It appears after a brand new clone / install, running the app and then turning on the "Enable Live Reload" feature that a new transformation is triggered but the iOS Simulator doesn't detect new changes to views, for example. Perhaps I'm missing a key element.

**Steps to reproduce ( Mac OS 10.11.4, Xcode 7.3 )**
- `git clone https://github.com/jhabdas/react-native-webpack-starter-kit.git native-starter-kit && cd $_`
- `npm i`
- open xcode project
- run project
- ctrl+cmd+z
- select "Enable Live Reload"
- change "Welcome to React Native!" in ./src/components/App.js to "Welcome to Reload!"
- unable to see changes unless a manual cmd+r is pressed

**Comment by jhabdas** [comment]
Thanks for the issue, @seanfuture. As React has moved forward they've started added development workflow affordances to React Native itself, as opposed to building them into a separate project (which I imagine will happen at some point). If you look at the React Native Webpack Server repo there is example integration for Hot Reloading, though I'm not sure if it still works as RN has updated. As a result, I purposely left it out of this kit.

FWIW I wouldn't worry too much about a perfect development experience. You'll likely spend a good amount of time working on stuff which causes rebuilds, and so having a really great hot loading pipeline will have no affordances there. I'll leave this issue open until I make it more clear why we're not using HMR (or the like) in the README.

**Comment by seanfuture** [comment]
Figured as much - Thanks kindly for clarifying.  Will take a look also when time permits.
