### ISSUE TITLE
node module 'react-native-scrollable-tab-view' missing file

### ISSUE THREAD

**Issue by weidaxu1988** [jhabdas/react-native-webpack-starter-kit#94]
I try to use node module 'react-native-scrollable-tab-view', but I got the following error

ERROR in ./~/react-native-scrollable-tab-view/DefaultTabBar.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Button in /Users/dawei/workspace/DingDong/node_modules/react-native-scrollable-tab-view
@ ./~/react-native-scrollable-tab-view/DefaultTabBar.js 10:13-32

The module export both Button.android.js and Button.ios.js as Button, and It seems like webpack cannot figure them out.
How can I config webpack to solve the problem?

**Comment by jhabdas** [comment]
Check out Lumpen Radio Webpack config, linked from README, for example using Webpack to manage a bundle with a RN native module called react-native-video as an example. Let me know how it goes!
